version: '3'
services:
  db:
    image: postgres
    container_name: delos-farm-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: developmentdb
      POSTGRES_DB: delos_farm
    ports:
      - "2345:5432"
    networks:
      - delos-farm-net
  app:
    build: .
    ports:
      - "7000:7000"
    container_name: delos-farm-app
    depends_on:
      - db
    env_file:
      - .env.docker
    networks:
      - delos-farm-net

networks:
  delos-farm-net:
