version: '3'
services:
  db:
    image: postgres
    container_name: delos-farm-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: developmentdb
      POSTGRES_DB: delos_farm
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    command: bash -c "while ! pg_isready -h 'db' -U postgres; do sleep 1; done; exec postgres -D /var/lib/postgresql/data"
  app:
    build: .
    ports:
      - "7000:9091"
    container_name: delos-farm-app
    depends_on:
      - db

volumes:
  db-data:
